build-job:
  stage: build
  script:
    - landscape2 build --data-file $CI_PROJECT_DIR/landscape.yml --settings-file $CI_PROJECT_DIR/settings.yml --logos-path $CI_PROJECT_DIR/hosted_logos --output-dir /home/$USER/output_landscape

deploy-prod:
  stage: deploy
  script:
    - cp -fr /home/$USER/output_landscape/* /var/www/html
  environment: production